# -*- coding: utf-8 -*-
from operator import attrgetter
from pyangbind.lib.yangtypes import RestrictedPrecisionDecimalType
from pyangbind.lib.yangtypes import RestrictedClassType
from pyangbind.lib.yangtypes import TypedListType
from pyangbind.lib.yangtypes import YANGBool
from pyangbind.lib.yangtypes import YANGListType
from pyangbind.lib.yangtypes import YANGDynClass
from pyangbind.lib.yangtypes import ReferenceType
from pyangbind.lib.base import PybindBase
from collections import OrderedDict
from decimal import Decimal
from bitarray import bitarray
import six

# PY3 support of some PY2 keywords (needs improved)
if six.PY3:
  import builtins as __builtin__
  long = int
elif six.PY2:
  import __builtin__

class yc_Aps_client_to_orc__ClientMac_Aps(PybindBase):
  """
  This class was auto-generated by the PythonClass plugin for PYANG
  from YANG module client_to_orc - based on the path /ClientMac/Aps. Each member element of
  the container is represented as a class variable - with a specific
  YANG type.
  """
  __slots__ = ('_path_helper', '_extmethods', '__Apmac','__signal',)

  _yang_name = 'Aps'

  _pybind_generated_by = 'container'

  def __init__(self, *args, **kwargs):

    self._path_helper = False

    self._extmethods = False
    self.__Apmac = YANGDynClass(base=RestrictedClassType(base_type=six.text_type, restriction_dict={u'pattern': u'[0-9a-fA-F]{2}(:[0-9a-fA-F]{2}){5}'}), is_leaf=True, yang_name="Apmac", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, is_keyval=True, namespace='https://client.com/client_to_orc', defining_module='client_to_orc', yang_type='mac-address', is_config=True)
    self.__signal = YANGDynClass(base=RestrictedClassType(base_type=Decimal, restriction_dict={u'range': [u'1..3.14', u'10', u'20..max']}), is_leaf=True, yang_name="signal", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='https://client.com/client_to_orc', defining_module='client_to_orc', yang_type='my-decimal', is_config=True)

    load = kwargs.pop("load", None)
    if args:
      if len(args) > 1:
        raise TypeError("cannot create a YANG container with >1 argument")
      all_attr = True
      for e in self._pyangbind_elements:
        if not hasattr(args[0], e):
          all_attr = False
          break
      if not all_attr:
        raise ValueError("Supplied object did not have the correct attributes")
      for e in self._pyangbind_elements:
        nobj = getattr(args[0], e)
        if nobj._changed() is False:
          continue
        setmethod = getattr(self, "_set_%s" % e)
        if load is None:
          setmethod(getattr(args[0], e))
        else:
          setmethod(getattr(args[0], e), load=load)

  def _path(self):
    if hasattr(self, "_parent"):
      return self._parent._path()+[self._yang_name]
    else:
      return [u'ClientMac', u'Aps']

  def _get_Apmac(self):
    """
    Getter method for Apmac, mapped from YANG variable /ClientMac/Aps/Apmac (mac-address)
    """
    return self.__Apmac
      
  def _set_Apmac(self, v, load=False):
    """
    Setter method for Apmac, mapped from YANG variable /ClientMac/Aps/Apmac (mac-address)
    If this variable is read-only (config: false) in the
    source YANG file, then _set_Apmac is considered as a private
    method. Backends looking to populate this variable should
    do so via calling thisObj._set_Apmac() directly.
    """
    parent = getattr(self, "_parent", None)
    if parent is not None and load is False:
      raise AttributeError("Cannot set keys directly when" +
                             " within an instantiated list")

    if hasattr(v, "_utype"):
      v = v._utype(v)
    try:
      t = YANGDynClass(v,base=RestrictedClassType(base_type=six.text_type, restriction_dict={u'pattern': u'[0-9a-fA-F]{2}(:[0-9a-fA-F]{2}){5}'}), is_leaf=True, yang_name="Apmac", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, is_keyval=True, namespace='https://client.com/client_to_orc', defining_module='client_to_orc', yang_type='mac-address', is_config=True)
    except (TypeError, ValueError):
      raise ValueError({
          'error-string': """Apmac must be of a type compatible with mac-address""",
          'defined-type': "client_to_orc:mac-address",
          'generated-type': """YANGDynClass(base=RestrictedClassType(base_type=six.text_type, restriction_dict={u'pattern': u'[0-9a-fA-F]{2}(:[0-9a-fA-F]{2}){5}'}), is_leaf=True, yang_name="Apmac", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, is_keyval=True, namespace='https://client.com/client_to_orc', defining_module='client_to_orc', yang_type='mac-address', is_config=True)""",
        })

    self.__Apmac = t
    if hasattr(self, '_set'):
      self._set()

  def _unset_Apmac(self):
    self.__Apmac = YANGDynClass(base=RestrictedClassType(base_type=six.text_type, restriction_dict={u'pattern': u'[0-9a-fA-F]{2}(:[0-9a-fA-F]{2}){5}'}), is_leaf=True, yang_name="Apmac", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, is_keyval=True, namespace='https://client.com/client_to_orc', defining_module='client_to_orc', yang_type='mac-address', is_config=True)


  def _get_signal(self):
    """
    Getter method for signal, mapped from YANG variable /ClientMac/Aps/signal (my-decimal)
    """
    return self.__signal
      
  def _set_signal(self, v, load=False):
    """
    Setter method for signal, mapped from YANG variable /ClientMac/Aps/signal (my-decimal)
    If this variable is read-only (config: false) in the
    source YANG file, then _set_signal is considered as a private
    method. Backends looking to populate this variable should
    do so via calling thisObj._set_signal() directly.
    """
    if hasattr(v, "_utype"):
      v = v._utype(v)
    try:
      t = YANGDynClass(v,base=RestrictedClassType(base_type=Decimal, restriction_dict={u'range': [u'1..3.14', u'10', u'20..max']}), is_leaf=True, yang_name="signal", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='https://client.com/client_to_orc', defining_module='client_to_orc', yang_type='my-decimal', is_config=True)
    except (TypeError, ValueError):
      raise ValueError({
          'error-string': """signal must be of a type compatible with my-decimal""",
          'defined-type': "client_to_orc:my-decimal",
          'generated-type': """YANGDynClass(base=RestrictedClassType(base_type=Decimal, restriction_dict={u'range': [u'1..3.14', u'10', u'20..max']}), is_leaf=True, yang_name="signal", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='https://client.com/client_to_orc', defining_module='client_to_orc', yang_type='my-decimal', is_config=True)""",
        })

    self.__signal = t
    if hasattr(self, '_set'):
      self._set()

  def _unset_signal(self):
    self.__signal = YANGDynClass(base=RestrictedClassType(base_type=Decimal, restriction_dict={u'range': [u'1..3.14', u'10', u'20..max']}), is_leaf=True, yang_name="signal", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='https://client.com/client_to_orc', defining_module='client_to_orc', yang_type='my-decimal', is_config=True)

  Apmac = __builtin__.property(_get_Apmac, _set_Apmac)
  signal = __builtin__.property(_get_signal, _set_signal)


  _pyangbind_elements = OrderedDict([('Apmac', Apmac), ('signal', signal), ])


class yc_Aps_client_to_orc__ClientMac_flows_Aps(PybindBase):
  """
  This class was auto-generated by the PythonClass plugin for PYANG
  from YANG module client_to_orc - based on the path /ClientMac/flows/Aps. Each member element of
  the container is represented as a class variable - with a specific
  YANG type.
  """
  __slots__ = ('_path_helper', '_extmethods', '__Apmac','__throughput',)

  _yang_name = 'Aps'

  _pybind_generated_by = 'container'

  def __init__(self, *args, **kwargs):

    self._path_helper = False

    self._extmethods = False
    self.__Apmac = YANGDynClass(base=RestrictedClassType(base_type=six.text_type, restriction_dict={u'pattern': u'[0-9a-fA-F]{2}(:[0-9a-fA-F]{2}){5}'}), is_leaf=True, yang_name="Apmac", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, is_keyval=True, namespace='https://client.com/client_to_orc', defining_module='client_to_orc', yang_type='mac-address', is_config=True)
    self.__throughput = YANGDynClass(base=RestrictedClassType(base_type=Decimal, restriction_dict={u'range': [u'1..3.14', u'10', u'20..max']}), is_leaf=True, yang_name="throughput", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='https://client.com/client_to_orc', defining_module='client_to_orc', yang_type='my-decimal', is_config=True)

    load = kwargs.pop("load", None)
    if args:
      if len(args) > 1:
        raise TypeError("cannot create a YANG container with >1 argument")
      all_attr = True
      for e in self._pyangbind_elements:
        if not hasattr(args[0], e):
          all_attr = False
          break
      if not all_attr:
        raise ValueError("Supplied object did not have the correct attributes")
      for e in self._pyangbind_elements:
        nobj = getattr(args[0], e)
        if nobj._changed() is False:
          continue
        setmethod = getattr(self, "_set_%s" % e)
        if load is None:
          setmethod(getattr(args[0], e))
        else:
          setmethod(getattr(args[0], e), load=load)

  def _path(self):
    if hasattr(self, "_parent"):
      return self._parent._path()+[self._yang_name]
    else:
      return [u'ClientMac', u'flows', u'Aps']

  def _get_Apmac(self):
    """
    Getter method for Apmac, mapped from YANG variable /ClientMac/flows/Aps/Apmac (mac-address)
    """
    return self.__Apmac
      
  def _set_Apmac(self, v, load=False):
    """
    Setter method for Apmac, mapped from YANG variable /ClientMac/flows/Aps/Apmac (mac-address)
    If this variable is read-only (config: false) in the
    source YANG file, then _set_Apmac is considered as a private
    method. Backends looking to populate this variable should
    do so via calling thisObj._set_Apmac() directly.
    """
    parent = getattr(self, "_parent", None)
    if parent is not None and load is False:
      raise AttributeError("Cannot set keys directly when" +
                             " within an instantiated list")

    if hasattr(v, "_utype"):
      v = v._utype(v)
    try:
      t = YANGDynClass(v,base=RestrictedClassType(base_type=six.text_type, restriction_dict={u'pattern': u'[0-9a-fA-F]{2}(:[0-9a-fA-F]{2}){5}'}), is_leaf=True, yang_name="Apmac", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, is_keyval=True, namespace='https://client.com/client_to_orc', defining_module='client_to_orc', yang_type='mac-address', is_config=True)
    except (TypeError, ValueError):
      raise ValueError({
          'error-string': """Apmac must be of a type compatible with mac-address""",
          'defined-type': "client_to_orc:mac-address",
          'generated-type': """YANGDynClass(base=RestrictedClassType(base_type=six.text_type, restriction_dict={u'pattern': u'[0-9a-fA-F]{2}(:[0-9a-fA-F]{2}){5}'}), is_leaf=True, yang_name="Apmac", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, is_keyval=True, namespace='https://client.com/client_to_orc', defining_module='client_to_orc', yang_type='mac-address', is_config=True)""",
        })

    self.__Apmac = t
    if hasattr(self, '_set'):
      self._set()

  def _unset_Apmac(self):
    self.__Apmac = YANGDynClass(base=RestrictedClassType(base_type=six.text_type, restriction_dict={u'pattern': u'[0-9a-fA-F]{2}(:[0-9a-fA-F]{2}){5}'}), is_leaf=True, yang_name="Apmac", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, is_keyval=True, namespace='https://client.com/client_to_orc', defining_module='client_to_orc', yang_type='mac-address', is_config=True)


  def _get_throughput(self):
    """
    Getter method for throughput, mapped from YANG variable /ClientMac/flows/Aps/throughput (my-decimal)
    """
    return self.__throughput
      
  def _set_throughput(self, v, load=False):
    """
    Setter method for throughput, mapped from YANG variable /ClientMac/flows/Aps/throughput (my-decimal)
    If this variable is read-only (config: false) in the
    source YANG file, then _set_throughput is considered as a private
    method. Backends looking to populate this variable should
    do so via calling thisObj._set_throughput() directly.
    """
    if hasattr(v, "_utype"):
      v = v._utype(v)
    try:
      t = YANGDynClass(v,base=RestrictedClassType(base_type=Decimal, restriction_dict={u'range': [u'1..3.14', u'10', u'20..max']}), is_leaf=True, yang_name="throughput", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='https://client.com/client_to_orc', defining_module='client_to_orc', yang_type='my-decimal', is_config=True)
    except (TypeError, ValueError):
      raise ValueError({
          'error-string': """throughput must be of a type compatible with my-decimal""",
          'defined-type': "client_to_orc:my-decimal",
          'generated-type': """YANGDynClass(base=RestrictedClassType(base_type=Decimal, restriction_dict={u'range': [u'1..3.14', u'10', u'20..max']}), is_leaf=True, yang_name="throughput", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='https://client.com/client_to_orc', defining_module='client_to_orc', yang_type='my-decimal', is_config=True)""",
        })

    self.__throughput = t
    if hasattr(self, '_set'):
      self._set()

  def _unset_throughput(self):
    self.__throughput = YANGDynClass(base=RestrictedClassType(base_type=Decimal, restriction_dict={u'range': [u'1..3.14', u'10', u'20..max']}), is_leaf=True, yang_name="throughput", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='https://client.com/client_to_orc', defining_module='client_to_orc', yang_type='my-decimal', is_config=True)

  Apmac = __builtin__.property(_get_Apmac, _set_Apmac)
  throughput = __builtin__.property(_get_throughput, _set_throughput)


  _pyangbind_elements = OrderedDict([('Apmac', Apmac), ('throughput', throughput), ])


class yc_flows_client_to_orc__ClientMac_flows(PybindBase):
  """
  This class was auto-generated by the PythonClass plugin for PYANG
  from YANG module client_to_orc - based on the path /ClientMac/flows. Each member element of
  the container is represented as a class variable - with a specific
  YANG type.
  """
  __slots__ = ('_path_helper', '_extmethods', '__ip_src','__ip_dst','__port','__Aps',)

  _yang_name = 'flows'

  _pybind_generated_by = 'container'

  def __init__(self, *args, **kwargs):

    self._path_helper = False

    self._extmethods = False
    self.__ip_dst = YANGDynClass(base=RestrictedClassType(base_type=six.text_type, restriction_dict={u'pattern': u'(([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])(%[\\p{N}\\p{L}]+)?'}), is_leaf=True, yang_name="ip_dst", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='https://client.com/client_to_orc', defining_module='client_to_orc', yang_type='ipv4-address', is_config=True)
    self.__port = YANGDynClass(base=RestrictedClassType(base_type=RestrictedClassType(base_type=int, restriction_dict={'range': ['0..65535']},int_size=16), restriction_dict={u'range': [u'0..65535']}), is_leaf=True, yang_name="port", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='https://client.com/client_to_orc', defining_module='client_to_orc', yang_type='port-number', is_config=True)
    self.__ip_src = YANGDynClass(base=RestrictedClassType(base_type=six.text_type, restriction_dict={u'pattern': u'(([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])(%[\\p{N}\\p{L}]+)?'}), is_leaf=True, yang_name="ip_src", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, is_keyval=True, namespace='https://client.com/client_to_orc', defining_module='client_to_orc', yang_type='ipv4-address', is_config=True)
    self.__Aps = YANGDynClass(base=YANGListType("Apmac",yc_Aps_client_to_orc__ClientMac_flows_Aps, yang_name="Aps", parent=self, is_container='list', user_ordered=False, path_helper=self._path_helper, yang_keys='Apmac', extensions=None), is_container='list', yang_name="Aps", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, extensions=None, namespace='https://client.com/client_to_orc', defining_module='client_to_orc', yang_type='list', is_config=True)

    load = kwargs.pop("load", None)
    if args:
      if len(args) > 1:
        raise TypeError("cannot create a YANG container with >1 argument")
      all_attr = True
      for e in self._pyangbind_elements:
        if not hasattr(args[0], e):
          all_attr = False
          break
      if not all_attr:
        raise ValueError("Supplied object did not have the correct attributes")
      for e in self._pyangbind_elements:
        nobj = getattr(args[0], e)
        if nobj._changed() is False:
          continue
        setmethod = getattr(self, "_set_%s" % e)
        if load is None:
          setmethod(getattr(args[0], e))
        else:
          setmethod(getattr(args[0], e), load=load)

  def _path(self):
    if hasattr(self, "_parent"):
      return self._parent._path()+[self._yang_name]
    else:
      return [u'ClientMac', u'flows']

  def _get_ip_src(self):
    """
    Getter method for ip_src, mapped from YANG variable /ClientMac/flows/ip_src (ipv4-address)
    """
    return self.__ip_src
      
  def _set_ip_src(self, v, load=False):
    """
    Setter method for ip_src, mapped from YANG variable /ClientMac/flows/ip_src (ipv4-address)
    If this variable is read-only (config: false) in the
    source YANG file, then _set_ip_src is considered as a private
    method. Backends looking to populate this variable should
    do so via calling thisObj._set_ip_src() directly.
    """
    parent = getattr(self, "_parent", None)
    if parent is not None and load is False:
      raise AttributeError("Cannot set keys directly when" +
                             " within an instantiated list")

    if hasattr(v, "_utype"):
      v = v._utype(v)
    try:
      t = YANGDynClass(v,base=RestrictedClassType(base_type=six.text_type, restriction_dict={u'pattern': u'(([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])(%[\\p{N}\\p{L}]+)?'}), is_leaf=True, yang_name="ip_src", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, is_keyval=True, namespace='https://client.com/client_to_orc', defining_module='client_to_orc', yang_type='ipv4-address', is_config=True)
    except (TypeError, ValueError):
      raise ValueError({
          'error-string': """ip_src must be of a type compatible with ipv4-address""",
          'defined-type': "client_to_orc:ipv4-address",
          'generated-type': """YANGDynClass(base=RestrictedClassType(base_type=six.text_type, restriction_dict={u'pattern': u'(([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])(%[\\p{N}\\p{L}]+)?'}), is_leaf=True, yang_name="ip_src", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, is_keyval=True, namespace='https://client.com/client_to_orc', defining_module='client_to_orc', yang_type='ipv4-address', is_config=True)""",
        })

    self.__ip_src = t
    if hasattr(self, '_set'):
      self._set()

  def _unset_ip_src(self):
    self.__ip_src = YANGDynClass(base=RestrictedClassType(base_type=six.text_type, restriction_dict={u'pattern': u'(([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])(%[\\p{N}\\p{L}]+)?'}), is_leaf=True, yang_name="ip_src", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, is_keyval=True, namespace='https://client.com/client_to_orc', defining_module='client_to_orc', yang_type='ipv4-address', is_config=True)


  def _get_ip_dst(self):
    """
    Getter method for ip_dst, mapped from YANG variable /ClientMac/flows/ip_dst (ipv4-address)
    """
    return self.__ip_dst
      
  def _set_ip_dst(self, v, load=False):
    """
    Setter method for ip_dst, mapped from YANG variable /ClientMac/flows/ip_dst (ipv4-address)
    If this variable is read-only (config: false) in the
    source YANG file, then _set_ip_dst is considered as a private
    method. Backends looking to populate this variable should
    do so via calling thisObj._set_ip_dst() directly.
    """
    if hasattr(v, "_utype"):
      v = v._utype(v)
    try:
      t = YANGDynClass(v,base=RestrictedClassType(base_type=six.text_type, restriction_dict={u'pattern': u'(([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])(%[\\p{N}\\p{L}]+)?'}), is_leaf=True, yang_name="ip_dst", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='https://client.com/client_to_orc', defining_module='client_to_orc', yang_type='ipv4-address', is_config=True)
    except (TypeError, ValueError):
      raise ValueError({
          'error-string': """ip_dst must be of a type compatible with ipv4-address""",
          'defined-type': "client_to_orc:ipv4-address",
          'generated-type': """YANGDynClass(base=RestrictedClassType(base_type=six.text_type, restriction_dict={u'pattern': u'(([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])(%[\\p{N}\\p{L}]+)?'}), is_leaf=True, yang_name="ip_dst", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='https://client.com/client_to_orc', defining_module='client_to_orc', yang_type='ipv4-address', is_config=True)""",
        })

    self.__ip_dst = t
    if hasattr(self, '_set'):
      self._set()

  def _unset_ip_dst(self):
    self.__ip_dst = YANGDynClass(base=RestrictedClassType(base_type=six.text_type, restriction_dict={u'pattern': u'(([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])(%[\\p{N}\\p{L}]+)?'}), is_leaf=True, yang_name="ip_dst", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='https://client.com/client_to_orc', defining_module='client_to_orc', yang_type='ipv4-address', is_config=True)


  def _get_port(self):
    """
    Getter method for port, mapped from YANG variable /ClientMac/flows/port (port-number)
    """
    return self.__port
      
  def _set_port(self, v, load=False):
    """
    Setter method for port, mapped from YANG variable /ClientMac/flows/port (port-number)
    If this variable is read-only (config: false) in the
    source YANG file, then _set_port is considered as a private
    method. Backends looking to populate this variable should
    do so via calling thisObj._set_port() directly.
    """
    if hasattr(v, "_utype"):
      v = v._utype(v)
    try:
      t = YANGDynClass(v,base=RestrictedClassType(base_type=RestrictedClassType(base_type=int, restriction_dict={'range': ['0..65535']},int_size=16), restriction_dict={u'range': [u'0..65535']}), is_leaf=True, yang_name="port", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='https://client.com/client_to_orc', defining_module='client_to_orc', yang_type='port-number', is_config=True)
    except (TypeError, ValueError):
      raise ValueError({
          'error-string': """port must be of a type compatible with port-number""",
          'defined-type': "client_to_orc:port-number",
          'generated-type': """YANGDynClass(base=RestrictedClassType(base_type=RestrictedClassType(base_type=int, restriction_dict={'range': ['0..65535']},int_size=16), restriction_dict={u'range': [u'0..65535']}), is_leaf=True, yang_name="port", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='https://client.com/client_to_orc', defining_module='client_to_orc', yang_type='port-number', is_config=True)""",
        })

    self.__port = t
    if hasattr(self, '_set'):
      self._set()

  def _unset_port(self):
    self.__port = YANGDynClass(base=RestrictedClassType(base_type=RestrictedClassType(base_type=int, restriction_dict={'range': ['0..65535']},int_size=16), restriction_dict={u'range': [u'0..65535']}), is_leaf=True, yang_name="port", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='https://client.com/client_to_orc', defining_module='client_to_orc', yang_type='port-number', is_config=True)


  def _get_Aps(self):
    """
    Getter method for Aps, mapped from YANG variable /ClientMac/flows/Aps (list)
    """
    return self.__Aps
      
  def _set_Aps(self, v, load=False):
    """
    Setter method for Aps, mapped from YANG variable /ClientMac/flows/Aps (list)
    If this variable is read-only (config: false) in the
    source YANG file, then _set_Aps is considered as a private
    method. Backends looking to populate this variable should
    do so via calling thisObj._set_Aps() directly.
    """
    if hasattr(v, "_utype"):
      v = v._utype(v)
    try:
      t = YANGDynClass(v,base=YANGListType("Apmac",yc_Aps_client_to_orc__ClientMac_flows_Aps, yang_name="Aps", parent=self, is_container='list', user_ordered=False, path_helper=self._path_helper, yang_keys='Apmac', extensions=None), is_container='list', yang_name="Aps", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, extensions=None, namespace='https://client.com/client_to_orc', defining_module='client_to_orc', yang_type='list', is_config=True)
    except (TypeError, ValueError):
      raise ValueError({
          'error-string': """Aps must be of a type compatible with list""",
          'defined-type': "list",
          'generated-type': """YANGDynClass(base=YANGListType("Apmac",yc_Aps_client_to_orc__ClientMac_flows_Aps, yang_name="Aps", parent=self, is_container='list', user_ordered=False, path_helper=self._path_helper, yang_keys='Apmac', extensions=None), is_container='list', yang_name="Aps", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, extensions=None, namespace='https://client.com/client_to_orc', defining_module='client_to_orc', yang_type='list', is_config=True)""",
        })

    self.__Aps = t
    if hasattr(self, '_set'):
      self._set()

  def _unset_Aps(self):
    self.__Aps = YANGDynClass(base=YANGListType("Apmac",yc_Aps_client_to_orc__ClientMac_flows_Aps, yang_name="Aps", parent=self, is_container='list', user_ordered=False, path_helper=self._path_helper, yang_keys='Apmac', extensions=None), is_container='list', yang_name="Aps", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, extensions=None, namespace='https://client.com/client_to_orc', defining_module='client_to_orc', yang_type='list', is_config=True)

  ip_src = __builtin__.property(_get_ip_src, _set_ip_src)
  ip_dst = __builtin__.property(_get_ip_dst, _set_ip_dst)
  port = __builtin__.property(_get_port, _set_port)
  Aps = __builtin__.property(_get_Aps, _set_Aps)


  _pyangbind_elements = OrderedDict([('ip_src', ip_src), ('ip_dst', ip_dst), ('port', port), ('Aps', Aps), ])


class yc_ClientMac_client_to_orc__ClientMac(PybindBase):
  """
  This class was auto-generated by the PythonClass plugin for PYANG
  from YANG module client_to_orc - based on the path /ClientMac. Each member element of
  the container is represented as a class variable - with a specific
  YANG type.
  """
  __slots__ = ('_path_helper', '_extmethods', '__Aps','__flows',)

  _yang_name = 'ClientMac'

  _pybind_generated_by = 'container'

  def __init__(self, *args, **kwargs):

    self._path_helper = False

    self._extmethods = False
    self.__Aps = YANGDynClass(base=YANGListType("Apmac",yc_Aps_client_to_orc__ClientMac_Aps, yang_name="Aps", parent=self, is_container='list', user_ordered=False, path_helper=self._path_helper, yang_keys='Apmac', extensions=None), is_container='list', yang_name="Aps", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, extensions=None, namespace='https://client.com/client_to_orc', defining_module='client_to_orc', yang_type='list', is_config=True)
    self.__flows = YANGDynClass(base=YANGListType("ip_src",yc_flows_client_to_orc__ClientMac_flows, yang_name="flows", parent=self, is_container='list', user_ordered=False, path_helper=self._path_helper, yang_keys='ip_src', extensions=None), is_container='list', yang_name="flows", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, extensions=None, namespace='https://client.com/client_to_orc', defining_module='client_to_orc', yang_type='list', is_config=True)

    load = kwargs.pop("load", None)
    if args:
      if len(args) > 1:
        raise TypeError("cannot create a YANG container with >1 argument")
      all_attr = True
      for e in self._pyangbind_elements:
        if not hasattr(args[0], e):
          all_attr = False
          break
      if not all_attr:
        raise ValueError("Supplied object did not have the correct attributes")
      for e in self._pyangbind_elements:
        nobj = getattr(args[0], e)
        if nobj._changed() is False:
          continue
        setmethod = getattr(self, "_set_%s" % e)
        if load is None:
          setmethod(getattr(args[0], e))
        else:
          setmethod(getattr(args[0], e), load=load)

  def _path(self):
    if hasattr(self, "_parent"):
      return self._parent._path()+[self._yang_name]
    else:
      return [u'ClientMac']

  def _get_Aps(self):
    """
    Getter method for Aps, mapped from YANG variable /ClientMac/Aps (list)
    """
    return self.__Aps
      
  def _set_Aps(self, v, load=False):
    """
    Setter method for Aps, mapped from YANG variable /ClientMac/Aps (list)
    If this variable is read-only (config: false) in the
    source YANG file, then _set_Aps is considered as a private
    method. Backends looking to populate this variable should
    do so via calling thisObj._set_Aps() directly.
    """
    if hasattr(v, "_utype"):
      v = v._utype(v)
    try:
      t = YANGDynClass(v,base=YANGListType("Apmac",yc_Aps_client_to_orc__ClientMac_Aps, yang_name="Aps", parent=self, is_container='list', user_ordered=False, path_helper=self._path_helper, yang_keys='Apmac', extensions=None), is_container='list', yang_name="Aps", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, extensions=None, namespace='https://client.com/client_to_orc', defining_module='client_to_orc', yang_type='list', is_config=True)
    except (TypeError, ValueError):
      raise ValueError({
          'error-string': """Aps must be of a type compatible with list""",
          'defined-type': "list",
          'generated-type': """YANGDynClass(base=YANGListType("Apmac",yc_Aps_client_to_orc__ClientMac_Aps, yang_name="Aps", parent=self, is_container='list', user_ordered=False, path_helper=self._path_helper, yang_keys='Apmac', extensions=None), is_container='list', yang_name="Aps", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, extensions=None, namespace='https://client.com/client_to_orc', defining_module='client_to_orc', yang_type='list', is_config=True)""",
        })

    self.__Aps = t
    if hasattr(self, '_set'):
      self._set()

  def _unset_Aps(self):
    self.__Aps = YANGDynClass(base=YANGListType("Apmac",yc_Aps_client_to_orc__ClientMac_Aps, yang_name="Aps", parent=self, is_container='list', user_ordered=False, path_helper=self._path_helper, yang_keys='Apmac', extensions=None), is_container='list', yang_name="Aps", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, extensions=None, namespace='https://client.com/client_to_orc', defining_module='client_to_orc', yang_type='list', is_config=True)


  def _get_flows(self):
    """
    Getter method for flows, mapped from YANG variable /ClientMac/flows (list)
    """
    return self.__flows
      
  def _set_flows(self, v, load=False):
    """
    Setter method for flows, mapped from YANG variable /ClientMac/flows (list)
    If this variable is read-only (config: false) in the
    source YANG file, then _set_flows is considered as a private
    method. Backends looking to populate this variable should
    do so via calling thisObj._set_flows() directly.
    """
    if hasattr(v, "_utype"):
      v = v._utype(v)
    try:
      t = YANGDynClass(v,base=YANGListType("ip_src",yc_flows_client_to_orc__ClientMac_flows, yang_name="flows", parent=self, is_container='list', user_ordered=False, path_helper=self._path_helper, yang_keys='ip_src', extensions=None), is_container='list', yang_name="flows", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, extensions=None, namespace='https://client.com/client_to_orc', defining_module='client_to_orc', yang_type='list', is_config=True)
    except (TypeError, ValueError):
      raise ValueError({
          'error-string': """flows must be of a type compatible with list""",
          'defined-type': "list",
          'generated-type': """YANGDynClass(base=YANGListType("ip_src",yc_flows_client_to_orc__ClientMac_flows, yang_name="flows", parent=self, is_container='list', user_ordered=False, path_helper=self._path_helper, yang_keys='ip_src', extensions=None), is_container='list', yang_name="flows", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, extensions=None, namespace='https://client.com/client_to_orc', defining_module='client_to_orc', yang_type='list', is_config=True)""",
        })

    self.__flows = t
    if hasattr(self, '_set'):
      self._set()

  def _unset_flows(self):
    self.__flows = YANGDynClass(base=YANGListType("ip_src",yc_flows_client_to_orc__ClientMac_flows, yang_name="flows", parent=self, is_container='list', user_ordered=False, path_helper=self._path_helper, yang_keys='ip_src', extensions=None), is_container='list', yang_name="flows", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, extensions=None, namespace='https://client.com/client_to_orc', defining_module='client_to_orc', yang_type='list', is_config=True)

  Aps = __builtin__.property(_get_Aps, _set_Aps)
  flows = __builtin__.property(_get_flows, _set_flows)


  _pyangbind_elements = OrderedDict([('Aps', Aps), ('flows', flows), ])


class client_to_orc(PybindBase):
  """
  This class was auto-generated by the PythonClass plugin for PYANG
  from YANG module client_to_orc - based on the path /client_to_orc. Each member element of
  the container is represented as a class variable - with a specific
  YANG type.
  """
  __slots__ = ('_path_helper', '_extmethods', '__ClientMac',)

  _yang_name = 'client_to_orc'

  _pybind_generated_by = 'container'

  def __init__(self, *args, **kwargs):

    self._path_helper = False

    self._extmethods = False
    self.__ClientMac = YANGDynClass(base=yc_ClientMac_client_to_orc__ClientMac, is_container='container', yang_name="ClientMac", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, extensions=None, namespace='https://client.com/client_to_orc', defining_module='client_to_orc', yang_type='container', is_config=True)

    load = kwargs.pop("load", None)
    if args:
      if len(args) > 1:
        raise TypeError("cannot create a YANG container with >1 argument")
      all_attr = True
      for e in self._pyangbind_elements:
        if not hasattr(args[0], e):
          all_attr = False
          break
      if not all_attr:
        raise ValueError("Supplied object did not have the correct attributes")
      for e in self._pyangbind_elements:
        nobj = getattr(args[0], e)
        if nobj._changed() is False:
          continue
        setmethod = getattr(self, "_set_%s" % e)
        if load is None:
          setmethod(getattr(args[0], e))
        else:
          setmethod(getattr(args[0], e), load=load)

  def _path(self):
    if hasattr(self, "_parent"):
      return self._parent._path()+[self._yang_name]
    else:
      return []

  def _get_ClientMac(self):
    """
    Getter method for ClientMac, mapped from YANG variable /ClientMac (container)
    """
    return self.__ClientMac
      
  def _set_ClientMac(self, v, load=False):
    """
    Setter method for ClientMac, mapped from YANG variable /ClientMac (container)
    If this variable is read-only (config: false) in the
    source YANG file, then _set_ClientMac is considered as a private
    method. Backends looking to populate this variable should
    do so via calling thisObj._set_ClientMac() directly.
    """
    if hasattr(v, "_utype"):
      v = v._utype(v)
    try:
      t = YANGDynClass(v,base=yc_ClientMac_client_to_orc__ClientMac, is_container='container', yang_name="ClientMac", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, extensions=None, namespace='https://client.com/client_to_orc', defining_module='client_to_orc', yang_type='container', is_config=True)
    except (TypeError, ValueError):
      raise ValueError({
          'error-string': """ClientMac must be of a type compatible with container""",
          'defined-type': "container",
          'generated-type': """YANGDynClass(base=yc_ClientMac_client_to_orc__ClientMac, is_container='container', yang_name="ClientMac", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, extensions=None, namespace='https://client.com/client_to_orc', defining_module='client_to_orc', yang_type='container', is_config=True)""",
        })

    self.__ClientMac = t
    if hasattr(self, '_set'):
      self._set()

  def _unset_ClientMac(self):
    self.__ClientMac = YANGDynClass(base=yc_ClientMac_client_to_orc__ClientMac, is_container='container', yang_name="ClientMac", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, extensions=None, namespace='https://client.com/client_to_orc', defining_module='client_to_orc', yang_type='container', is_config=True)

  ClientMac = __builtin__.property(_get_ClientMac, _set_ClientMac)


  _pyangbind_elements = OrderedDict([('ClientMac', ClientMac), ])


